### ISSUE TITLE
Intermittent crash

### ISSUE THREAD

**Issue by lwchkg** [lwchkg/gitbook-plugin-sunlight-highlighter#3]
Stack trace:
```
TypeError: First argument to Node.prototype.replaceChild must be a Node
    at HTMLDivElementImpl.replaceChild (D:\Documents\pCloud Sync\gitbook\vbnet_intro\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:279:13)
    at HTMLDivElement.replaceChild (D:\Documents\pCloud Sync\gitbook\vbnet_intro\node_modules\jsdom\lib\jsdom\living\generated\Node.js:146:58)
    at d.G [as highlightNode] (D:\Documents\pCloud Sync\gitbook\vbnet_intro\node_modules\gitbook-plugin-sunlight-highlighter\sunlight-all-min.js:1:12073)
    at highlight (D:\Documents\pCloud Sync\gitbook\vbnet_intro\node_modules\gitbook-plugin-sunlight-highlighter\babel-out\index.js:77:17)
    at Object.code (D:\Documents\pCloud Sync\gitbook\vbnet_intro\node_modules\gitbook-plugin-sunlight-highlighter\babel-out\index.js:95:14)
    at Record.TemplateBlock.applyBlock (C:\Users\user\.gitbook\versions\3.2.2\lib\models\templateBlock.js:205:23)
    at C:\Users\user\.gitbook\versions\3.2.2\lib\output\getModifiers.js:56:33
    at C:\Users\user\.gitbook\versions\3.2.2\lib\output\modifiers\highlightCode.js:47:24
    at C:\Users\user\.gitbook\versions\3.2.2\lib\output\modifiers\editHTMLElement.js:11:16
    at C:\Users\user\.gitbook\versions\3.2.2\lib\utils\promise.js:36:16
```

**Comment by lwchkg** [comment]
Close because sunlight.min.js is no longer a dependency.
